import { ZERG_EXTENSION_VERSION, type ZergControlAction, type ZergControlHelpData, type ZergControlHelpParameter } from './types.js';

type ActionName = ZergControlAction['action'];
export interface ZergControlHelpEntry {
  action: ActionName;
  group: string;
  summary: string;
  parameters: readonly ZergControlHelpParameter[];
  constraints: readonly string[];
  effects: readonly string[];
  example: ZergControlAction;
  restrictions: readonly string[];
}
const parameter = (name: string, type: string, required: boolean, description: string): ZergControlHelpParameter => ({ name, type, required, description });
const id = parameter('id', 'string', true, 'Configuration identity; nonempty. Agent IDs normalize trim/lowercase, whitespace/underscore to hyphen, and remove edge hyphens.');
const model = parameter('model', 'string', false, 'Model policy/override; provider/model[:thinking] recommended. Ordinary native runs also accept available unqualified IDs; omitted uses configured policy or SDK default.');
const fallbackModels = parameter('fallbackModels', 'string[]', false, 'Fallback model list; defaults to configured policy. Agent saves trim/deduplicate/sort names. Current native runner rejects nonempty fallback lists; external adapters may support them.');
const maxTurns = parameter('maxTurns', 'number', false, 'Positive safe integer turn budget; defaults to configured policy. Current native runner rejects turn limits; external adapters may support them. Not a time/cost limit.');
const configRestrictions = ['Changes configuration, not execution authority; does not start work.', 'These legacy configuration handlers do not enforce mode.readOnly; do not use them for a read-only task.'];
const executionRestrictions = ['Caller task and permission constraints still apply. Read-only mode blocks launch; legacy run can still queue a permission request/log, not execute work.', 'An available runner and compatible model/tool policy are required; this call does not grant broader authority.'];
const exactSession = ['parentRunId', 'memberRunId', 'piSessionId'].map(name => parameter(name, 'string', true, 'Exact recorded session identity, 1..256 characters; no whitespace/control characters or fallback.'));
const exactExample = { parentRunId: 'zerg-run', memberRunId: 'zerg-member', piSessionId: 'pi-session' };
const workflowRun = parameter('workflowRunId', 'string', true, 'Exact existing workflow attempt ID; no active-run fallback.');
const definitionId = parameter('definitionId', 'string', true, 'Exact saved workflow definition ID (definition IDs: 1..80, letters/digits/underscore/dot/hyphen, leading letter/digit).');
const workflowRestrictions = ['Existing workflow ownership, admission and frozen model/tool policies apply.', 'Execution requires non-read-only caller authority; coding also requires trusted host opt-in and separate implementation/application gates. JSON cannot grant approvals.'];
const workflowReadRestrictions = ['Inspection does not execute work or grant authority.', 'Ordinary workflow inspection can initialize/publish an empty lazy ledger; only help is entirely static.'];
const sourceParameters = [parameter('source', 'string', true, 'Restricted workflow source, at most 65536 UTF8 bytes and UTF16 code units; interpreted as data, not arbitrary JavaScript.'), parameter('sourceName', 'string', false, 'Display-only label, at most 128 characters/512 UTF8 bytes; compiler default workflow.workflow.js.')];
const sourceExample = 'workflow({id:"example",label:"Example",inputSchema:{type:"object",properties:{},additionalProperties:false}},()=>{const result=aggregate("result",{dependsOn:[],operation:"collect",inputs:{value:value("ok")}});});';
const scriptRestrictions = ['No approvals or autostart; execution is a separate workflows.start call.', 'Validation/compilation uses a bounded owned compiler subprocess (5000ms total deadline), not provider/model calls or arbitrary JS.'];
const recoveryRestrictions = ['Read-only artifact/owner assessment only; prepare is NOT authorization and cannot execute recovered work.', 'Trusted host recovery confirmation and exact fingerprint/settlement evidence remain separate, with fresh coding gates. No replay, takeover or reconnection is implied.'];
function entry(action: ActionName, group: string, summary: string, parameters: readonly ZergControlHelpParameter[], effects: readonly string[], example: ZergControlAction, constraints: readonly string[] = [], restrictions: readonly string[] = []): ZergControlHelpEntry {
  return { action, group, summary, parameters: [parameter('action', JSON.stringify(action), true, 'Exact public action name.'), ...parameters], constraints, effects, example, restrictions };
}

/** Static public tool surface only. Trusted approvals/authorization are deliberately absent.
 * The exhaustive record makes action-union changes require a discovery entry. */
export const ZERG_CONTROL_HELP_CATALOG = {
  help: entry('help', 'Discovery', 'List actions or inspect exact action arguments.', [parameter('topic', 'string', false, 'Exact public action name, 1..96 characters; absent/undefined lists all actions. No trimming, aliases or fuzzy matching.')], ['static inspection'], { action: 'help' }, ['Only action and topic own fields are accepted.'], ['No state, persistence, transcript, workflow initialization, subprocess or provider effects. Works without terminal UI and in read-only mode.']),
  status: entry('status', 'Inspection', 'Inspect version, mode, counts and persistence status.', [], ['inspection'], { action: 'status' }),
  'agents.list': entry('agents.list', 'Inspection', 'List configured agent definitions.', [], ['inspection'], { action: 'agents.list' }),
  'agents.show': entry('agents.show', 'Inspection', 'Show one agent definition.', [id], ['inspection'], { action: 'agents.show', id: 'generalist' }, ['The definition must exist.']),
  'agents.create': entry('agents.create', 'Configuration', 'Save an agent definition.', [id, parameter('prompt', 'string', true, 'Nonempty prompt, trimmed when saved.'), parameter('label', 'string', false, 'Display label; defaults to id.'), parameter('description', 'string', false, 'Optional description.'), model, fallbackModels, maxTurns, parameter('tools', 'string[]', false, 'Tool allowlist; absent native defaults are read/bash. [] explicitly means no tools. Native aliases include files, shell and larra/mcp; denied tools are subtracted.'), parameter('disallowedTools', 'string[]', false, 'Excluded tools; names trimmed/deduplicated.'), parameter('permissionMode', '"manual" | "assisted" | "automatic" | "inherit"', false, 'Definition permission policy; absent inherits caller policy. Native runner rejects manual/assisted; inherit/default or automatic is supported.')], ['configuration write', 'log/persistence publication'], { action: 'agents.create', id: 'helper', prompt: 'Inspect only; do not modify files.' }, ['Existing ID is upserted, not a duplicate error.'], configRestrictions),
  'agents.update': entry('agents.update', 'Configuration', 'Update an existing agent definition.', [id, parameter('prompt', 'string', false, 'Nonempty prompt; defaults to existing prompt.'), parameter('label', 'string', false, 'Defaults to existing label.'), parameter('description', 'string', false, 'Defaults to existing description.'), model, fallbackModels, maxTurns, parameter('tools', 'string[]', false, 'Defaults to existing allowlist; [] selects no tools. Native absent default is read/bash.'), parameter('disallowedTools', 'string[]', false, 'Defaults to existing exclusions.'), parameter('permissionMode', '"manual" | "assisted" | "automatic" | "inherit"', false, 'Defaults to existing definition policy; native rejects manual/assisted.')], ['configuration write', 'log/persistence publication'], { action: 'agents.update', id: 'generalist', label: 'Generalist' }, ['ID must exist; omitted fields retain existing values.'], configRestrictions),
  'agents.delete': entry('agents.delete', 'Configuration', 'Delete an existing agent definition.', [id], ['configuration write', 'persistence publication'], { action: 'agents.delete', id: 'helper' }, ['ID must exist. Does not cancel running sessions.'], configRestrictions),
  'team.create': entry('team.create', 'Configuration', 'Save team configuration.', [id, parameter('label', 'string', false, 'Defaults to existing label or id.'), parameter('leader', 'string', false, 'Leader agent definition ID; required for later runnable team launch.'), parameter('members', 'string[]', false, 'Member definition IDs; defaults to existing members or [].'), parameter('kind', '"team" | "squad" | "worktree"', false, 'Defaults to existing kind or team; kind does not itself create a Git worktree.'), model, fallbackModels, maxTurns], ['configuration write', 'log/persistence publication'], { action: 'team.create', id: 'review-team', leader: 'generalist', members: ['reviewer'] }, ['Existing team ID is updated; definitions are checked on launch, not here.'], configRestrictions),
  'team.update': entry('team.update', 'Configuration', 'Update an existing team.', [id, parameter('label', 'string', false, 'Defaults to existing label.'), parameter('leader', 'string', false, 'Defaults to existing leader definition ID.'), parameter('members', 'string[]', false, 'Defaults to existing members.'), parameter('kind', '"team" | "squad" | "worktree"', false, 'Defaults to existing kind; not Git worktree creation.'), model, fallbackModels, maxTurns], ['configuration write', 'log/persistence publication'], { action: 'team.update', id: 'review-team', label: 'Review team' }, ['Team ID must exist; omitted fields retain existing values.'], configRestrictions),
  run: entry('run', 'Execution', 'Launch a configured agent or native team.', [parameter('agent', 'string', true, 'Agent definition or team ID. A team needs a runnable leader and all member definitions.'), parameter('task', 'string', true, 'Nonempty caller task, preserving permission constraints.'), parameter('background', 'boolean', false, 'Defaults false: await completion when the adapter supports it. True returns admission, not completion.'), parameter('launchMode', '"fresh" | "fork"', false, 'Defaults fresh. Current native runner rejects fork before SDK startup; only an adapter implementing fork may use it. Never recovered-session reconnection.'), parameter('concurrency', 'number', false, 'Positive safe integer, default 8; per-run native team worker concurrency, not workflow concurrency.'), model, fallbackModels, maxTurns], ['native execution', 'state/log/persistence writes'], { action: 'run', agent: 'generalist', task: 'Inspect the repository without modifying files.' }, ['Direct/leader run overrides take precedence over configured policy; native team members retain their explicit models when present. Native rejects fork, maxTurns and nonempty fallbackModels in request or leader/member definitions.'], executionRestrictions),
  'runs.list': entry('runs.list', 'Inspection', 'List retained native run snapshots.', [], ['inspection'], { action: 'runs.list' }, [], ['A recovered snapshot is not a reconnected live session.']),
  'runs.show': entry('runs.show', 'Inspection', 'Show an exact native run.', [parameter('runId', 'string', true, 'Existing native run ID; adapter fallback may inspect the same exact ID.')], ['inspection'], { action: 'runs.show', runId: 'zerg-run' }),
  'timeline.list': entry('timeline.list', 'Inspection', 'Inspect bounded recorded activity and receipts.', ['teamId', 'parentRunId', 'memberRunId', 'piSessionId'].map(name => parameter(name, 'string', false, 'Exact filter ID, 1..256 characters, no whitespace/control characters; omitted means unfiltered.')).concat([parameter('limit', 'number', false, 'Safe integer 1..256, default 128.')]), ['retained-state inspection'], { action: 'timeline.list' }, [], ['No transcript reads; bounded retained activity is not a full conversation or delivery history. Team attribution uses recorded IDs, not current membership.']),
  'logs.list': entry('logs.list', 'Inspection', 'List retained structured log records.', [parameter('runId', 'string', false, 'Exact run filter; omitted means all retained runs.'), parameter('level', '"debug" | "info" | "warn" | "error"', false, 'Exact level filter; omitted means all levels.'), parameter('limit', 'number', false, 'Positive finite numbers are floored; omitted/nonpositive/nonfinite uses 200. No additional request cap; retained ledger bounds available records. Values between 0 and 1 floor to 0 and return the retained filtered records.')], ['inspection'], { action: 'logs.list', limit: 20 }),
  message: entry('message', 'Session control', 'Send a legacy agent/team-routed operator message.', [parameter('targetId', 'string', true, 'Agent/team target; team routing follows its leader.'), parameter('body', 'string', true, 'Nonempty literal message body.'), parameter('runId', 'string', false, 'Optional run routing scope; omission allows adapter routing.'), parameter('mode', '"steer" | "followUp"', false, 'Defaults steer. Use followUp for a queued follow-up.')], ['message transport', 'state/log/persistence writes'], { action: 'message', targetId: 'generalist', body: 'Report findings only.' }, [], ['Read-only mode blocks messaging. Requires accepting owned live transport; recording/admission alone is not confirmed delivery. Workflow frozen inputs cannot be steered.']),
  interrupt: entry('interrupt', 'Session control', 'Request cancellation of a native run.', [parameter('runId', 'string', false, 'Exact run ID; omitted uses active native run.')], ['cancellation', 'state/log/persistence writes'], { action: 'interrupt', runId: 'zerg-run' }, [], ['Requires interrupt-capable adapter. Read-only mode blocks cancellation and queues a permission request/log instead; approval is separate. Cancellation is not proof that native cleanup has settled.']),
  'session.message.send': entry('session.message.send', 'Session control', 'Send to one exact owned native session.', [...exactSession, parameter('messageId', 'string', true, 'Deduplication ID, 1..128 characters, no whitespace/controls. Same ID/payload can return the existing receipt; conflicting reuse fails.'), parameter('body', 'string', true, 'Nonempty literal text, at most 16384 characters; forbidden controls rejected.'), parameter('mode', '"steer" | "followUp"', true, 'Explicit delivery mode; no default.')], ['exact message transport', 'receipt/persistence writes'], { action: 'session.message.send', ...exactExample, messageId: 'message-1', body: 'Report findings only.', mode: 'followUp' }, [], ['Read-only mode blocks sends. Exact accepting live owner required; unavailable/recovered or frozen workflow unit sessions cannot receive steering.', 'Receipts distinguish recording, queuing, confirmation and uncertainty; native output is not an addressed reply.']),
  'session.messages.list': entry('session.messages.list', 'Inspection', 'Inspect one exact session receipt ledger.', [...exactSession, parameter('limit', 'number', false, 'Safe integer 1..128; default 32.')], ['receipt inspection'], { action: 'session.messages.list', ...exactExample }, [], ['Retained receipts only; no delivery, replay or transcript reads.']),
  'session.continuation.prepare': entry('session.continuation.prepare', 'Continuation', 'Prepare review for a new independent task from selected history.', [...exactSession, parameter('entryId', 'string', true, 'Exact eligible native history entry, 1..256 characters, no whitespace/controls.'), parameter('body', 'string', true, 'New literal task, nonempty, at most 16384 characters; unsafe controls rejected.'), parameter('model', 'string', false, 'Explicit provider/model[:thinking] override up to 512 characters; otherwise current definition policy.'), parameter('acknowledgeUnconfirmedSource', 'boolean', false, 'Default false; true explicitly acknowledges an unavailable detached source, not its liveness.')], ['bounded transcript/context reads', 'ephemeral review creation'], { action: 'session.continuation.prepare', ...exactExample, entryId: 'entry-1', body: 'Inspect the selected findings without modifying files.' }, ['Review expires after 5 minutes; at most 16 retained reviews.'], ['Requires available continuation service; preparation permits read-only inspection. Only start checks execution admission authority. Preparation does not launch, reconnect, adopt or resume the source.', 'Attached source is rejected: wait for disposal. Unsupported history/policy is rejected; start separately confirms a reviewed task.']),
  'session.continuation.start': entry('session.continuation.start', 'Continuation', 'Confirm a prepared independent continuation task.', [parameter('reviewId', 'string', true, 'Exact unexpired review returned by prepare; consumed on admission attempt.'), parameter('confirm', 'true', true, 'Explicit literal true; no implied confirmation.')], ['new native execution', 'history/context copying', 'state/persistence writes'], { action: 'session.continuation.start', reviewId: 'review-1', confirm: true }, ['Source fingerprints and current policy are revalidated; stale/expired review requires prepare again.'], executionRestrictions),
  'session.continuation.discard': entry('session.continuation.discard', 'Continuation', 'Discard a prepared review without launch.', [parameter('reviewId', 'string', true, 'Review ID; absent token is harmless.')], ['ephemeral review removal'], { action: 'session.continuation.discard', reviewId: 'review-1' }, [], ['Requires continuation service; no native execution.']),
  'workflows.list': entry('workflows.list', 'Workflow inspection', 'List compact workflow attempts and definitions.', [], ['inspection', 'possible lazy ledger publication'], { action: 'workflows.list' }, [], workflowReadRestrictions),
  'workflows.define': entry('workflows.define', 'Workflow authoring', 'Validate and save a bounded declarative graph.', [parameter('definition', 'WorkflowDefinition', true, 'Plain JSON {id,version,label,inputSchema,steps,authoring?}; version 1|2|3. At most 65536 UTF8 bytes, 16 authored steps, fanout 32, 256 expanded units; typed bindings/schemas, no arbitrary tools/code. IDs 1..80 with leading letter/digit then letters/digits/_.-; nonempty label <=160.')], ['definition/persistence write', 'lazy workflow initialization'], { action: 'workflows.define', definition: { id: 'example', version: 1, label: 'Example', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, steps: [{ id: 'result', kind: 'aggregate', dependsOn: [], operation: 'collect', inputs: { value: { value: 'ok' } } }] } }, ['At most 16 saved definitions; same ID replacement requires no unsettled run. Does not start work.'], workflowRestrictions),
  'workflows.show': entry('workflows.show', 'Workflow inspection', 'Inspect an exact definition or workflow attempt.', [parameter('definitionId', 'string', false, 'Exact saved definition ID; mutually exclusive with workflowRunId.'), parameter('workflowRunId', 'string', false, 'Exact attempt ID; mutually exclusive with definitionId.')], ['inspection', 'possible lazy ledger publication'], { action: 'workflows.show', definitionId: 'example' }, ['Exactly one of definitionId/workflowRunId is required. Attempt view includes bounded matching approval previews, not callable approval grants.'], workflowReadRestrictions),
  'workflows.start': entry('workflows.start', 'Workflow execution', 'Start a saved workflow with frozen input and policy.', [definitionId, parameter('inputs', 'JSON', true, 'Schema-valid plain finite JSON, at most 32768 UTF8 bytes; never permissions. Supply {} for empty object input.'), parameter('concurrency', 'number', false, 'Safe integer 1..32, default 8; per-workflow admission cap, subject to owner global cap.')], ['workflow/native execution', 'state/persistence writes'], { action: 'workflows.start', definitionId: 'example', inputs: {} }, ['At most 16 retained attempts; agent definitions must exist with explicit compatible read-only model/tool policy. Native workflow agents reject maxTurns, fallbackModels and permission overrides other than inherit; need at least one authorized read/grep/find/ls builtin. Coding uses separately configured trusted policy.'], workflowRestrictions),
  'workflows.pause': entry('workflows.pause', 'Workflow execution', 'Pause further scheduling of a running workflow.', [workflowRun], ['workflow state/persistence write'], { action: 'workflows.pause', workflowRunId: 'workflow-1' }, ['Only running attempts; in-flight work is not undone.'], ['Does not grant execution authority or prove native cleanup.']),
  'workflows.resume': entry('workflows.resume', 'Workflow execution', 'Resume a live paused workflow under existing authority.', [workflowRun], ['workflow/native scheduling', 'state/persistence writes'], { action: 'workflows.resume', workflowRunId: 'workflow-1' }, ['Only live paused, non-recovered attempts; frozen policy and caller authority rechecked.'], workflowRestrictions),
  'workflows.cancel': entry('workflows.cancel', 'Workflow execution', 'Cancel pending/in-flight workflow work.', [workflowRun], ['cancellation', 'state/persistence writes'], { action: 'workflows.cancel', workflowRunId: 'workflow-1' }, [], ['Cancellation is not proof of native/check cleanup settlement; no recovery authorization.']),
  'workflows.retry': entry('workflows.retry', 'Workflow execution', 'Admit a fresh attempt for a settled failed/cancelled workflow.', [workflowRun], ['new workflow/native execution', 'state/persistence writes'], { action: 'workflows.retry', workflowRunId: 'workflow-1' }, ['Latest family attempt only; cleanup settled, fewer than 3 attempts and 256 cumulative admissions. Reuses frozen definition/inputs/concurrency, not prior native sessions.', 'Recovered or linked recovery attempts cannot use ordinary retry.'], workflowRestrictions),
  'workflows.report': entry('workflows.report', 'Workflow inspection', 'Inspect a retained workflow report and view.', [workflowRun], ['inspection', 'possible lazy ledger publication'], { action: 'workflows.report', workflowRunId: 'workflow-1' }, ['Report may be absent until produced.'], workflowReadRestrictions),
  'workflows.forget': entry('workflows.forget', 'Workflow authoring', 'Remove a settled terminal attempt from retained workflow state.', [workflowRun], ['retained-state/persistence write'], { action: 'workflows.forget', workflowRunId: 'workflow-1' }, ['Terminal and cleanup-settled only; cannot remove referenced recovery family anchors, sources, selections or provenance. Does not delete external artifacts.'], workflowRestrictions),
  'workflows.recovery.inspect': entry('workflows.recovery.inspect', 'Recovery assessment', 'Inspect inert recovered-work evidence.', [parameter('workflowRunId', 'string', true, 'Exact existing ID, 1..160 characters, leading letter/digit then letters/digits/underscore/dot/colon/hyphen.')], ['read-only owner/artifact assessment'], { action: 'workflows.recovery.inspect', workflowRunId: 'workflow-1' }, ['Only action/workflowRunId fields; missing ledger does not initialize one.'], recoveryRestrictions),
  'workflows.recovery.prepare': entry('workflows.recovery.prepare', 'Recovery assessment', 'Prepare a non-executing recovery projection.', [parameter('workflowRunId', 'string', true, 'Exact existing ID, 1..160 characters, leading letter/digit then letters/digits/underscore/dot/colon/hyphen.'), parameter('selections', '{reuseUnitIds?: string[], rerunUnitIds?: string[]}', false, 'Optional disjoint duplicate-free arrays, at most 256 IDs each; IDs 1..160, leading letter/digit then letters/digits/._:@/-; omit for default assessment.')], ['read-only owner/artifact assessment'], { action: 'workflows.recovery.prepare', workflowRunId: 'workflow-1' }, ['Only action/workflowRunId/selections fields; prepare does not initialize a missing ledger.'], recoveryRestrictions),
  'workflows.scripts.validate': entry('workflows.scripts.validate', 'Script authoring', 'Compile restricted source and return inspection only.', sourceParameters, ['owned compiler subprocess'], { action: 'workflows.scripts.validate', source: sourceExample }, ['Only action/source/sourceName fields; no save, graph registration or lazy workflow initialization.'], scriptRestrictions),
  'workflows.scripts.compile': entry('workflows.scripts.compile', 'Script authoring', 'Return the bounded compiled graph and inspection.', sourceParameters, ['owned compiler subprocess'], { action: 'workflows.scripts.compile', source: sourceExample }, ['Only action/source/sourceName fields; no save or lazy workflow initialization.'], scriptRestrictions),
  'workflows.scripts.inspect': entry('workflows.scripts.inspect', 'Script authoring', 'Inspect a saved graph and authoring metadata without compilation.', [definitionId], ['saved-state inspection'], { action: 'workflows.scripts.inspect', definitionId: 'example' }, ['Only action/definitionId fields; exactly one saved matching definition; no compiler or lazy workflow initialization.'], ['Does not execute work or certify current model availability/approval.']),
  'workflows.scripts.save': entry('workflows.scripts.save', 'Script authoring', 'Compile source then explicitly save the graph.', sourceParameters, ['owned compiler subprocess', 'definition/persistence write'], { action: 'workflows.scripts.save', source: sourceExample }, ['Only action/source/sourceName fields. Same retention, authority and unsettled-replacement gates as workflows.define.'], [...scriptRestrictions, ...workflowRestrictions]),
  'workflows.scripts.import': entry('workflows.scripts.import', 'Script authoring', 'Read one explicit local script, compile and save it.', [parameter('path', 'string', true, 'Normalized relative-cwd path, 1..1024 characters/at most 64 components; no dot/dotdot, backslashes, colon, controls, absolute paths, symlinks or nonregular files. Linux descriptor-safe walk; file at most 65536 bytes, strict UTF8.')], ['local file read', 'owned compiler subprocess', 'definition/persistence write'], { action: 'workflows.scripts.import', path: 'example.workflow.js' }, ['Only action/path fields; no scanning, watching or automatic start; same gates as workflows.define.'], [...scriptRestrictions, ...workflowRestrictions]),
} satisfies Record<ActionName, ZergControlHelpEntry>;

// Freeze only our finite static metadata, never caller input or live state.
function freezeStatic(value: unknown): void {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return;
  for (const child of Object.values(value)) freezeStatic(child);
  Object.freeze(value);
}
freezeStatic(ZERG_CONTROL_HELP_CATALOG);
export const ZERG_CONTROL_ACTION_NAMES: readonly ActionName[] = Object.freeze(Object.keys(ZERG_CONTROL_HELP_CATALOG) as ActionName[]);
export function isZergControlActionName(value: unknown): value is ActionName {
  return typeof value === 'string' && Object.hasOwn(ZERG_CONTROL_HELP_CATALOG, value);
}
/** Echo at most 96 printable ASCII characters plus a truncation marker; no terminal controls. */
export function controlHelpEcho(value: unknown): string {
  return typeof value === 'string' ? value.slice(0, 96).replace(/[^\x20-\x7e]/g, '?') + (value.length > 96 ? '...' : '') : '(invalid)';
}
export function unknownControlActionMessage(value: unknown): string {
  return `Unknown zerg_control action: ${controlHelpEcho(value)}. Use {"action":"help"} to list supported actions.`;
}
export function validateControlHelpRequest(input: unknown): string | undefined {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return 'help requires an object with action and optional exact topic.';
  const keys = Reflect.ownKeys(input);
  if (keys.some(key => key !== 'action' && key !== 'topic')) return 'help accepts only action and optional topic. Use {"action":"help"}.';
  if (keys.some(key => !Object.hasOwn(Object.getOwnPropertyDescriptor(input, key)!, 'value'))) return 'help requires plain data fields, not accessors.';
  const { topic } = input as { topic?: unknown };
  if (topic !== undefined && (typeof topic !== 'string' || topic.length < 1 || topic.length > 96)) return 'help topic must be an exact public action name (1..96 characters). Use {"action":"help"} to list actions.';
  if (topic !== undefined && !isZergControlActionName(topic)) return `Unknown zerg_control help topic: ${controlHelpEcho(topic)}. Use {"action":"help"} to list supported actions.`;
  return undefined;
}
export function getZergControlHelpData(topic?: ActionName): ZergControlHelpData {
  if (topic !== undefined) {
    const { group: _group, ...focused } = ZERG_CONTROL_HELP_CATALOG[topic];
    return { version: ZERG_EXTENSION_VERSION, kind: 'action', ...focused };
  }
  const groups: Extract<ZergControlHelpData, { kind: 'directory' }>['groups'] = [];
  for (const action of ZERG_CONTROL_ACTION_NAMES) {
    const info = ZERG_CONTROL_HELP_CATALOG[action];
    let group = groups.find(item => item.name === info.group);
    if (!group) { group = { name: info.group, actions: [] }; groups.push(group); }
    group.actions.push({ action, summary: info.summary, effects: [...info.effects] });
  }
  return { version: ZERG_EXTENSION_VERSION, kind: 'directory', groups, hint: 'Use {"action":"help","topic":"<exact action name>"} for parameters, constraints and a JSON example.', restrictions: ['Help is static, bounded and read-only; examples are data, not execution requests.', 'Other actions may inspect, change configuration, launch work or require existing authority. Read-only intent is not automatic permission to mutate.', 'Recovery prepare is not authorization. Trusted host approval/recovery APIs are not public tool actions.'] };
}
